version: '3.7'

services:
  mysql-files:
    container_name: mysql-files
    image: mysql:5
    expose:
      - 3306
    ports:
      - 3306:3306
    networks:
      general-project:
        ipv4_address: "172.16.238.11"
    environment:
      TZ: America/Sao_Paulo
      MYSQL_DATABASE: files
      MYSQL_USER: user-files
      MYSQL_PASSWORD: password-files
      MYSQL_ROOT_PASSWORD: root

networks:
  general-project:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24


