version: '3.7'

services:
  mysql-files:
    container_name: mysql-files
    image: mysql:5
    expose:
      - 3306
    ports:
      - 3306:3306
    networks:
      general-project:
        ipv4_address: "172.16.238.11"
    environment:
      TZ: America/Sao_Paulo
      MYSQL_DATABASE: files
      MYSQL_USER: user-files
      MYSQL_PASSWORD: password-files
      MYSQL_ROOT_PASSWORD: root

  file-process-project:
    container_name: file-process-project
    build:
      context: .
      dockerfile: Dockerfile
    image: github.com/patriciaramos1995/file-process-project
    restart: always
    environment:
      TZ: America/Sao_Paulo
      JAVA_OPTS: -Xmx512m -Dfile.encoding=UTF-8  -Duser.Timezone=America/Sao_Paulo -Duser.country=BR -Duser.language=pt"
    volumes:
      - $HOME/data/in/:/data/in/
      - $HOME/data/out/:/data/out/
    ports:
      - "8090:8090"
    networks:
      general-project:
        ipv4_address: "172.16.238.10"
    depends_on:
      - mysql-files

networks:
  general-project:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24


