server.port: 8090
spring:
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/files?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: user-files
    password: password-files
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate.generate_statistics: false
  batch:
    initialize-schema: always

file.path:
  input: ${user.home}/data/in/
  output: ${user.home}/data/out/